export const ERR = {
  NO_AUTENTICADO: 'NO_AUTENTICADO',
  MASCOTA_REQUERIDA: 'MASCOTA_REQUERIDA',
  MASCOTAS_REQUERIDAS: 'MASCOTAS_REQUERIDAS',
  MASCOTA_NO_ENCONTRADA: 'MASCOTA_NO_ENCONTRADA',
  MASCOTA_NO_PERTENECE_AL_USUARIO: 'MASCOTA_NO_PERTENECE_AL_USUARIO',
  PASEO_NO_ENCONTRADO: 'PASEO_NO_ENCONTRADO',
  PASEO_NO_ES_MULTIPLE: 'PASEO_NO_ES_MULTIPLE',
  ESTADO_DEL_PASEO_NO_ACEPTA_MASCOTAS: 'ESTADO_DEL_PASEO_NO_ACEPTA_MASCOTAS',
  LIMITE_DE_MASCOTAS_SUPERADO: 'LIMITE_DE_MASCOTAS_SUPERADO',
  MASCOTA_YA_AGREGADA: 'MASCOTA_YA_AGREGADA',
  DUENO_NO_COINCIDE: 'DUENO_NO_COINCIDE',
  ERROR_DESCONOCIDO: 'ERROR_DESCONOCIDO',

  // Auth (Firebase)
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS', // wrong-password, invalid-credential
  AUTH_USER_NOT_FOUND: 'AUTH_USER_NOT_FOUND',
  AUTH_EMAIL_IN_USE: 'AUTH_EMAIL_IN_USE',
  AUTH_WEAK_PASSWORD: 'AUTH_WEAK_PASSWORD',
  AUTH_OPERATION_NOT_ALLOWED: 'AUTH_OPERATION_NOT_ALLOWED',
  AUTH_TOO_MANY_REQUESTS: 'AUTH_TOO_MANY_REQUESTS',
  AUTH_USER_DISABLED: 'AUTH_USER_DISABLED',
  AUTH_INVALID_EMAIL: 'AUTH_INVALID_EMAIL',
  AUTH_NETWORK_ERROR: 'AUTH_NETWORK_ERROR',
} as const

export type ErrorCode = (typeof ERR)[keyof typeof ERR]
