export const ERR = {
  COMUN: {
    NO_AUTENTICADO: 'NO_AUTENTICADO',
    PERMISOS_INSUFICIENTES: 'PERMISOS_INSUFICIENTES',
    DOCUMENTO_NO_ENCONTRADO: 'DOCUMENTO_NO_ENCONTRADO',
    ERROR_DESCONOCIDO: 'ERROR_DESCONOCIDO',
    DATOS_INVALIDOS: 'DATOS_INVALIDOS',
  },

  AUTH: {
    CREDENCIALES_INVALIDAS: 'CREDENCIALES_INVALIDAS',
    USUARIO_NO_ENCONTRADO: 'USUARIO_NO_ENCONTRADO',
    CORREO_EN_USO: 'CORREO_EN_USO',
    PASSWORD_DEBIL: 'PASSWORD_DEBIL',
    OPERACION_NO_PERMITIDA: 'OPERACION_NO_PERMITIDA',
    DEMASIADOS_INTENTOS: 'DEMASIADOS_INTENTOS',
    USUARIO_DESHABILITADO: 'USUARIO_DESHABILITADO',
    CORREO_INVALIDO: 'CORREO_INVALIDO',
    ERROR_RED: 'ERROR_RED',
  },

  MASCOTAS: {
    MASCOTA_REQUERIDA: 'MASCOTA_REQUERIDA',
    MASCOTAS_REQUERIDAS: 'MASCOTAS_REQUERIDAS',
    MASCOTA_NO_ENCONTRADA: 'MASCOTA_NO_ENCONTRADA',
    MASCOTA_NO_PERTENECE_AL_USUARIO: 'MASCOTA_NO_PERTENECE_AL_USUARIO',
    MASCOTA_YA_AGREGADA: 'MASCOTA_YA_AGREGADA',
    TUTOR_NO_COINCIDE: 'TUTOR_NO_COINCIDE',
  },

  PASEOS: {
    PASEO_NO_ENCONTRADO: 'PASEO_NO_ENCONTRADO',
    PASEO_NO_ES_COMPARTIDO: 'PASEO_NO_ES_COMPARTIDO',
    ESTADO_DEL_PASEO_NO_ACEPTA_MASCOTAS: 'ESTADO_DEL_PASEO_NO_ACEPTA_MASCOTAS',
    LIMITE_DE_MASCOTAS_SUPERADO: 'LIMITE_DE_MASCOTAS_SUPERADO',
  },
} as const

// Tipo utilitario para obtener los valores profundos (hojas) de ERR
type DeepValues<T> = T extends string
  ? T
  : T extends object
    ? { [K in keyof T]: DeepValues<T[K]> }[keyof T]
    : never

export type ErrorCode = DeepValues<typeof ERR>
